function gameState = ReadGameState()
    channelID = 2981355;
    
    % This is available from https://thingspeak.com/account/profile
    userAPIKey = 'BOVH3LOEU1YE2CC2'; 

    % Insert your own API keys here
    readKey = '90X7QDWKM2IQXQFR';

    data = thingSpeakRead(channelID, "ReadKey", readKey, "Fields", [1, 2, 3, 4, 5, 6, 7], "OutputFormat", "table", "NumPoints", 100)

    gameState(height(data), 1) = struct('turnNumber', [], ...
                                    'playerID', [], ...
                                    'turnScore', [], ...
                                    'accumulatedScore', [], ...
                                    'event', [], ...
                                    'dice', [], ...
                                    'rerollCount', []);

    for i = 1:height(data)

        diceDecoded = data.diceEncoded{i};
        diceDecoded = str2num(diceDecoded);

        object = struct('turnNumber', data.turnNumber(i), ...
                'playerID', data.playerID(i), ...
                'turnScore', data.turnScore(i), ...
                'accumulatedScore', data.accumulatedScore(i), ...
                'event', data.event(i), ...
                'dice', diceDecoded, ...
                'rerollCount', data.rerollCount(i));

        gameState(i) = object;
    end



end
